name: Build Signed Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > my-release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build Signed APK & AAB
        run: |
          yes "n" | bubblewrap build \
            --jdkPath "$JAVA_HOME" \
            --skipPwaValidation \
            --signingKeyPath my-release-key.keystore \
            --signingKeyAlias "${{ secrets.KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.KEY_PASSWORD }}" \
            --signingStorePassword "${{ secrets.KEYSTORE_PASSWORD }}" \
            --generateAppBundle

      # Upload artifacts (Bubblewrap outputs them under ./android/app/build/outputs/)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: |
            ./app-release-signed.apk
            ./android/app/build/outputs/**/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: |
            ./app-release-bundle.aab
            ./android/app/build/outputs/**/*.aab
