name: Build Android APK

on:
  push:
    branches: [ "main" ]  # change if your default branch is different
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          bubblewrap build --skipPwaValidation --skipSigning

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./app-release-signed.apk
