name: Build Signed Android App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli
        
      - name: Verify Bubblewrap installation
        run: bubblewrap --version
        
      - name: Check for twa-manifest.json
        run: |
          if [ ! -f "twa-manifest.json" ]; then
            echo "Error: twa-manifest.json not found!"
            echo "Please create a twa-manifest.json file in your repository root."
            exit 1
          fi
          cat twa-manifest.json
          
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > my-release-key.keystore
          ls -la my-release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: Verify keystore
        run: |
          keytool -list -keystore my-release-key.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -v
        continue-on-error: true
        
      - name: Build Signed APK & AAB
        run: |
          bubblewrap build \
            --skipUpdateChecks \
            --skipPwaValidation \
            --signingKeyPath my-release-key.keystore \
            --signingKeyAlias "${{ secrets.KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.KEY_PASSWORD }}" \
            --signingStorePassword "${{ secrets.KEYSTORE_PASSWORD }}" \
            --generateAppBundle
            
      - name: List generated files
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Looking for APK and AAB files:"
          find . -name "*.apk" -o -name "*.aab"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: |
            **/*.apk
            app-release-signed.apk
        if: success()
        
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: |
            **/*.aab
            app-release-bundle.aab
        if: success()
