name: Build Signed Android App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli
        
      - name: Setup Android SDK
        run: |
          # Install Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
      - name: Install Android Build Tools
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0" "platforms;android-33"
        
      - name: Check for twa-manifest.json
        run: |
          if [ ! -f "twa-manifest.json" ]; then
            echo "Error: twa-manifest.json not found!"
            echo "Please create a twa-manifest.json file in your repository root."
            exit 1
          fi
          cat twa-manifest.json
          
      - name: Decode Keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > my-release-key.keystore
          ls -la my-release-key.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: Verify keystore
        run: |
          keytool -list -keystore my-release-key.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -v
        continue-on-error: true
        
      - name: Build Signed APK & AAB
        run: |
          bubblewrap build \
            --skipUpdateChecks \
            --skipPwaValidation \
            --signingKeyPath my-release-key.keystore \
            --signingKeyAlias "${{ secrets.KEY_ALIAS }}" \
            --signingKeyPassword "${{ secrets.KEY_PASSWORD }}" \
            --signingStorePassword "${{ secrets.KEYSTORE_PASSWORD }}" \
            --generateAppBundle
            
      - name: List generated files
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Looking for APK and AAB files:"
          find . -name "*.apk" -o -name "*.aab"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: |
            **/*.apk
            app-release-signed.apk
        if: success()
        
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: |
            **/*.aab
            app-release-bundle.aab
        if: success()
